# Generated by Django 4.1.1 on 2022-10-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
